### ISSUE TITLE
Add option to load custom javascript

### ISSUE THREAD

**Issue by ImBobby** [ImBobby/suit-baze#28]
as discussed, using this technique and load sequentially
```Javascript
<script data-src="file-1.js"></script>
<script data-src="file-2.js"></script>
```

**Comment by ImBobby** [comment]
Put on hold due to yepnope has been removed from modernizr

**Comment by feryardiant** [comment]
Any plan using **require.js**??

**Comment by ImBobby** [comment]
No, since we are not adopting module system in Suit-baze. What we need simply assets loader. Closing this issue 45eb646ed6e1ae208d489231d65e5e6a73dc086e

**Comment by feryardiant** [comment]
:+1:
