### ISSUE TITLE
gulp-minify-css is deprecated

### ISSUE THREAD

**Issue by ImBobby** [ImBobby/suit-baze#34]
Warning message suggested to use gulp-cssnano instead.

**Comment by ImBobby** [comment]
Put on hold due to cssnano performance issue. Sticking to gulp-minify-css. https://github.com/murphydanger/gulp-minify-css/issues/135

**Comment by ImBobby** [comment]
https://github.com/scniro/gulp-clean-css

**Comment by feryardiant** [comment]
+1 for clean-css, here's the comparison between both of them

![image](https://cloud.githubusercontent.com/assets/508665/13841894/f75355f6-ec5d-11e5-8513-10c2bd235086.png)
__top: cssnano, bottom: clean-css

done using this tips: jakubpawlowicz/clean-css#342

**Comment by feryardiant** [comment]
:+1:

On Apr 8, 2016 16:08, Bobby <notifications@github.com> wrote:

Closed #34 via 24903a2.
